version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./packages/server/.env
    environment:
      - PORT=5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
