version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./packages/server/.env.database
    environment:
      - PORT=5432
