import { PropsWithChildren } from "react";
import "../styles/index.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
